version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - daily-app

  server:
    image: daily-server-dev:latest
    container_name: server
    restart: always
    ports:
      - 8080:8080
    networks:
      - daily-app
    volumes:
      - ./.env:/usr/src/app/.env
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - mongo

networks:
  daily-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
